'use strict';
document.documentElement.classList.add('js');
const menu=document.querySelector('.menu-button'),nav=document.querySelector('#navigation');
menu.hidden=false;menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus();}});
const filters=[...document.querySelectorAll('[data-filter]')],cards=[...document.querySelectorAll('[data-category]')];
filters.forEach(button=>button.addEventListener('click',()=>{filters.forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});cards.forEach(c=>c.hidden=button.dataset.filter!=='all'&&c.dataset.category!==button.dataset.filter);document.querySelector('#gallery-count').textContent=cards.filter(c=>!c.hidden).length+' images';}));
const links=[...document.querySelectorAll('[data-gallery]')],dialog=document.querySelector('#lightbox');let current=0,lastTrigger;
function showImage(index){current=(index+links.length)%links.length;const a=links[current],img=dialog.querySelector('#lightbox-image');img.src=a.href;img.alt=a.querySelector('img').alt;dialog.querySelector('#lightbox-title').textContent=a.querySelector('.caption h2').textContent;dialog.querySelector('#lightbox-caption').textContent=a.querySelector('.caption p').textContent;dialog.querySelector('#lightbox-position').textContent=(current+1)+' / '+links.length;}
if(dialog){links.forEach((a,i)=>a.addEventListener('click',e=>{if(typeof dialog.showModal!=='function')return;e.preventDefault();lastTrigger=a;showImage(i);dialog.showModal();document.body.classList.add('modal-open');}));document.querySelector('#close-lightbox').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastTrigger?.focus();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});document.querySelector('#prev-image').onclick=()=>showImage(current-1);document.querySelector('#next-image').onclick=()=>showImage(current+1);dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();showImage(current-1);}if(e.key==='ArrowRight'){e.preventDefault();showImage(current+1);}});}
function openService(){const id=location.hash.slice(1),el=document.getElementById(id);if(el?.tagName==='DETAILS')el.open=true;}openService();window.addEventListener('hashchange',openService);
const form=document.querySelector('#brief-form');let brief='';
if(form){const query=new URLSearchParams(location.search).get('service'),select=form.querySelector('#service');if([...select.options].some(o=>o.value===query))select.value=query;
form.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(form);if(!String(f.get('details')).trim()){form.elements.details.setCustomValidity('Please describe your project.');form.elements.details.reportValidity();return;}brief=['JAMTRAC — PROJECT BRIEF','DRAFT ONLY — NOT SENT','',`Type of work: ${f.get('service')}`,`Preferred timing: ${f.get('timing')}`,`Location: ${String(f.get('location')).trim()||'Not specified'}`,'','PROJECT DESCRIPTION',String(f.get('details')).trim(),'','OTHER DETAILS',String(f.get('notes')).trim()||'None added','', 'Prepared locally. This brief has not been sent to JAMTRAC.'].join('\n');document.querySelector('#brief-output').textContent=brief;const result=document.querySelector('#brief-result');result.hidden=false;document.querySelector('#brief-status').textContent='Your draft is ready. Nothing has been sent.';result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});const heading=document.querySelector('#brief-title');heading.tabIndex=-1;heading.focus({preventScroll:true});});
form.elements.details.addEventListener('input',()=>form.elements.details.setCustomValidity(''));
document.querySelector('#download-brief').onclick=()=>{const url=URL.createObjectURL(new Blob([brief],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='JAMTRAC-project-brief.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#brief-status').textContent='Download requested. Your brief has not been sent to JAMTRAC.';};document.querySelector('#print-brief').onclick=()=>window.print();}
